### ISSUE TITLE
Use symfony autowiring

### ISSUE THREAD

**Issue by lucasaba** [lucasaba/GitlabTimeTrack#17]
I had to deifne the gitlab request service, like in prev 3.3 version, as public:
```yml
gitlabtimetrack.request_service:
        class: AppBundle\Service\GitlabRequestService
        arguments: [ '@eight_points_guzzle.client.api_gitlab', '@monolog.logger' ]
        public: true
```
While it should use the new service definition:
https://symfony.com/doc/current/service_container/autowiring.html
